//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAGA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactPersonalInfo
    {
        public int ContactID { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<int> HeightInches { get; set; }
        public Nullable<int> WeightPounds { get; set; }
        public string DietaryRestrictions { get; set; }
    }
}
